### ISSUE TITLE
What do the different colors mean?

### ISSUE THREAD

**Issue by hanniabu** [crypto-jobs-fyi/crawler#3]
On https://crypto-jobs-fyi.github.io/web/ the different rows have different colors. A legend would be helpful here.

**Comment by yury-dubinin** [comment]
It basically a color coding for a role type based on a filter from web repo. Have a look here https://github.com/crypto-jobs-fyi/web/blob/main/site_builder.py#L70

But good point, I will add a legend.

**Comment by yury-dubinin** [comment]
Okay, I have added a color coding legend by applying a background color to links to corresponding job types.
<img width="1122" alt="image" src="https://github.com/crypto-jobs-fyi/crawler/assets/62520712/d08cdff7-8635-403e-a84c-4e3d2ad7cf15">

**Comment by hanniabu** [comment]
Great addition!
