### ISSUE TITLE
I have a similar repository

### ISSUE THREAD

**Issue by douglasdcm** [crypto-jobs-fyi/crawler#4]
Hi, how are you? Congratulations for the initiative! I was checking this repository and it is very similar of [one](https://github.com/douglasdcm/job-conqueror) I have. My repository is intended to get jobs from lots of companies and post them in a Web Page. I improved it to run asynchronously, maybe the code [here](https://github.com/douglasdcm/caqui/blob/main/sample.py) may inspire/help you to do the same. I noticed the code runs 30% faster using the async way than the sync one.
If you have any question, check the [README](https://github.com/douglasdcm/caqui) or send it to me. Lets help people to get jobs easier!

I1m forking this repo to check how can I help it to grow!

**Comment by yury-dubinin** [comment]
I have a plan to run jobs concurrently but want to consider running them in multiple docker containers. But need to change how the output is stored first. Will refactor over the weekend.
